INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('GEN', 'Gn.', 'Génesis', 'Génesis', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('EXO', 'Ex.', 'Éxodo', 'Éxodo', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('LEV', 'Lv.', 'Levítico', 'Levítico', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('NUM', 'Nm.', 'Números', 'Números', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('DEU', 'Dt.', 'Deuteronomio', 'Deuteronomio', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JOS', 'Jos.', 'Josué', 'Josué', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JDG', 'Jue.', 'Jueces', 'Jueces', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('RUT', 'Rt.', 'Rut', 'Rut', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1SA', '1 S.', '1 Samuel', 'Primer libro de Samuel', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2SA', '2 S.', '2 Samuel', 'Segundo libro de Samuel', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1KI', '1 R.', '1 Reyes', 'Primer libro de los Reyes', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2KI', '2 R.', '2 Reyes', 'Segundo libro de los Reyes', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1CH', '1 Cr.', '1 Crónicas', 'Primer libro de las Crónicas', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2CH', '2 Cr.', '2 Crónicas', 'Segundo libro de las Crónicas', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('EZR', 'Esd.', 'Esdras', 'Esdras', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('NEH', 'Neh.', 'Nehemías', 'Nehemías', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('EST', 'Est.', 'Ester', 'Ester', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JOB', 'Job', 'Job', 'Job', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('PSA', 'Sal.', 'Salmos', 'Salmos', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('PRO', 'Pr.', 'Proverbios', 'Proverbios', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('ECC', 'Ec.', 'Eclesiastés', 'Eclesiastés', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('SNG', 'Cnt.', 'Cantares', 'El Cantar de los Cantares', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('ISA', 'Is.', 'Isaías', 'Isaías', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JER', 'Jer.', 'Jeremías', 'Jeremías', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('LAM', 'Lm.', 'Lamentaciones', 'Lamentaciones', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('EZK', 'Ez.', 'Ezequiel', 'Ezequiel', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('DAN', 'Dn.', 'Daniel', 'Daniel', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('HOS', 'Os.', 'Oseas', 'Oseas', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JOL', 'Jl.', 'Joel', 'Joel', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('AMO', 'Am.', 'Amós', 'Amós', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('OBA', 'Abd.', 'Abdías', 'Abdías', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JON', 'Jon.', 'Jonás', 'Jonás', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('MIC', 'Mi.', 'Miqueas', 'Miqueas', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('NAM', 'Nah.', 'Nahúm', 'Nahúm', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('HAB', 'Hab.', 'Habacuc', 'Habacuc', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('ZEP', 'Sof.', 'Sofonías', 'Sofonías', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('HAG', 'Hag.', 'Hageo', 'Hageo', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('ZEC', 'Zac.', 'Zacarías', 'Zacarías', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('MAL', 'Mal.', 'Malaquías', 'Malaquías', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('MAT', 'Mt.', 'San Mateo', 'Evangelio según San Mateo', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('MRK', 'Mr.', 'San Marcos', 'Evangelio según San Marcos', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('LUK', 'Lc.', 'San Lucas', 'Evangelio según San Lucas', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JHN', 'Jn.', 'San Juan', 'Evangelio según San Juan', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('ACT', 'Hch.', 'Hechos', 'Hechos de los Apóstoles', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('ROM', 'Ro.', 'Romanos', 'Carta de san Pablo a los Romanos', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1CO', '1 Co.', '1 Corintios', 'Primera carta de san Pablo a los Corintios', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2CO', '2 Co.', '2 Corintios', 'Segunda carta de san Pablo a los Corintios', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('GAL', 'Ga.', 'Gálatas', 'Carta de san Pablo a los Gálatas', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('EPH', 'Ef.', 'Efesios', 'Carta de san Pablo a los Efesios', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('PHP', 'Fil.', 'Filipenses', 'Carta de san Pablo a los Filipenses', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('COL', 'Col.', 'Colosenses', 'Carta de san Pablo a los Colosenses', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1TH', '1 Ts.', '1 Tesalonicenses', 'Primera carta de san Pablo a los Tesalonicenses', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2TH', '2 Ts.', '2 Tesalonicenses', 'Segunda carta de san Pablo a los Tesalonicenses', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1TI', '1 Ti.', '1 Timoteo', 'Primera carta de san Pablo a Timoteo', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2TI', '2 Ti.', '2 Timoteo', 'Segunda carta de san Pablo a Timoteo', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('TIT', 'Tit.', 'Tito', 'Carta de san Pablo a Tito', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('PHM', 'Flm.', 'Filemón', 'Carta de san Pablo a Filemón', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('HEB', 'He.', 'Hebreos', 'Carta a los Hebreos', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JAS', 'Stg.', 'Santiago', 'Carta de Santiago', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1PE', '1 P.', '1 Pedro', 'Primera carta de san Pedro', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2PE', '2 P.', '2 Pedro', 'Segunda carta de san Pedro', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('1JN', '1 Jn.', '1 Juan', 'Primera carta de san Juan', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('2JN', '2 Jn.', '2 Juan', 'Segunda carta de san Juan', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('3JN', '3 Jn.', '3 Juan', 'Tercera carta de san Juan', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('JUD', 'Jud.', 'Judas', 'Carta de san Judas', 'RVR09');
INSERT INTO book (id, abbreviation, name,  "nameLong", "bibleId") VALUES ('REV', 'Ap.', 'Apocalipsis', 'Apocalipsis', 'RVR09');